using WebShard.Ioc;

namespace WebShard
{
    public class TestController
    {
        public IResponse Index()
        {
            return new ContentResponse(@"
<!doctype html>
<html>
    <head>
        <title>WebServer test application controller</title>
    </head>
    <body>
        <h2>Test web server</h2>
        <p>This is a test document generated by the test controller.</p>
    </body>
</html>
");
        }
    }

    class Program
    {
        static void Main()
        {
            var app = new HttpApplication();

            app.ControllerRegistry.Register<TestController>();
            app.RouteTable.Add("/{controller}/{action}/{id?}", new { controller = "Test", action = "Index" });

            var server = new HttpWebServer(80, 443, app);
            
            server.Start();
        }
    }
}
