using WebShard.Filtering;
using WebShard.Ioc;
using WebShard.Routing;

namespace WebShard
{
    public class TestController
    {

        private readonly IHttpRequestContext _request;

        public TestController(IHttpRequestContext request)
        {
            _request = request;
        }

        public IResponse Get()
        {
            return new ContentResponse(@"
<!doctype html>
<html>
    <head>
        <title>WebServer test application controller</title>
    </head>
    <body>
        <h2>Test web server</h2>
        <p>This is a test document generated by the test controller.</p>
        Your endpoing is <strong>" + _request.RemoteAddress + @"</strong>.
    </body>
</html>
");
        }
    }

    class Program
    {
        static void Main()
        {
            var app = new HttpApplication();

            app.ControllerRegistry.Register<TestController>();
            app.RouteTable.Add("/{controller?}", new { controller = "Test" });          

            var server = new HttpWebServer(app);

            server.Start();
        }
    }
}
